#+TITLE: I Want a Beard
#+AUTHOR: Paco Pascal
#+DATE: Fall, 2013
#+OPTIONS: toc:nil num:nil

My father and I were sitting at the table of Nana's house. I was
munching on a loaf of Italian bread and my father was sipping
coffee. It was the good kind with uneven pockets of air and the
perfect amount of flour on the crust. The table was rectangular. He
was sitting at the corner of the shorter side while I was near him at
the long side.

My 11 year old self looks up at my father and says "I want a beard."

He casually says, "You need to be 21."

"21!?" I answer back with a sense of surprise and confusion.

"Yeah."

"But.. Since, since when do you need to be 21?"

"It's always been like that."

"But doesn't it just happen? What are you supposed to do if you get
one before you're 21?"

"You can't have it then, you got to get rid of it."

"Really? You have to shave it off?"

"What?"

"You have to shave off your beard if you're not 21?"

"Beard?" my father realizing the confusion begins to laugh. "I thought
you said 'beer'."

"No! Not beer, beard! I don't wanna beer." I say with a laugh.

My father finding this confusing conversation amusing calls in Nana to
tell her the funny anecdote.


A year later I lost all contact with him. I never saw him again. At
16, some weak peachy facial hair began to sprout. And at 21, I grew a
proper beard.
