#+TITLE: The Unintentional Invention of Meat
#+SUBTITLE: A Story from Calais Hobbes
#+AUTHOR: Paco Pascal
#+DATE: November 5, 2011
#+OPTIONS: toc:nil num:nil

My problem began manifesting during the years of my elementary
studies. I was young then and although I did not have much knowledge
of society, my problem gave me a feeling of awkwardness. Throughout my
life I felt like a sore thumb, constantly reminding its owner that its
existence differs a little from his other fingers. Overall I was an
average child. Nothing about me was statistically abnormal in either
direction. Like most people of the society, my education began and
continued successfully; my hair was a thick curly black; both my eyes
were bright green, given I was not sexually mature at the time. After
reaching sexual maturity, my left eye became blue. Despite my overall
lack of uniqueness, I possessed the most statistically abnormal
feature to ever exist.

During my childhood, my mother Satu Hobbes and father Henry Hobbes,
frequently took me for visits to various woodlands and
grasslands. While on one of our frequent visits, gracklers were
surrounding us, eating mossy plants. While one was resting peacefully
near my feet, I grabbed it and bit its neck.

"Oh God! Calais, what are you doing!?" I recall my mother shrieked.

After being startled, I quickly dropped the grackler. Mother and
Father ran over in shock.

"Calais! Why would you do such a thing?" Mother questioned nervously.

"I don't know" I muttered. "I was curious how the grackler
tasted. They appear tasteful."

My cheeks became red and I was filled with shame. My seven year old
mind was conflicted between the urge to taste the grackler and the
disapproval of my parents. Seeing what was troubling my parents about
biting the grackler was difficult for me to see. Attempting to eat a
grackler or another animal seemed to be the natural course of action.

"Why do you wonder what they taste like, Calais?" Father asked
sincerely.

"I have a feeling that eating a grackler would be tasty." I replied
honestly, attempting not to be ashamed.

"A feeling you say? Feelings can be deceiving. Do not always trust
your feelings. Next time you get such a feeling, try to reason through
the feeling. Analyze it."

I nodded in response to his warm and understanding advice. As he
patted my back, Mother began to calm.

"Okay, Calais. Let's go home, you have your studies tomorrow." Mother
stated.

That night as I laid myself down to sleep, I attempted to analyze the
situation. Where did the urge come from? I tried that night to figure
out what the cause of the urge was; alas, my 7 year old mind was
unable to fully analyze the feeling.

"Food has always been plants. I've never seen or heard of someone
using an animal as food. I've also never seen or heard of an animal
using another animal as food. So, why would I get a feeling that
forced me to think of a grackler as food?" I thought to myself.

"Would I want to eat another human?" I asked myself while fearing my
response. "Definitely not! The thought of eating a human frightens
me." Being assured that the urge to eat animals did not extend to
eating humans, I slept well.

* . . .


What was the stem of this desire? I have wondered this since that
night. The urge began as spontaneous, but gradually became a familiar
presence. Our understanding of biological life demonstrates that
between the two distinct evolutionary trees, only one is a source of
food; specifically, a source of food for the species of the other
evolutionary tree.

Musgi are strange creatures. Their process of reproduction through
becoming gases then slowly condensing is very different from the
species in our evolutionary tree, the Hingi. Most Musgi have even
adapted to our digestive processes. Their reproduction is directly
influenced and stimulated by going through our digestive system. When
a Hingi consumes a Musgi, the result for most Musgi is
multiplication. Our tree evolved completely independently from the
Musgi tree. There is no common ancestor for the species of the Musgi
and Hingi. Though, I wonder if I should not be strict with the
previous statement. Is there an unknown common ancestor?

The relationship between the Musgi and Hingi is very distinct. Our
source of energy is provided by the Musgi and their method of
reproduction is assisted by us; but, if a common ancestor exists, then
every Hingi is the food of another Hingi.

* . . .

My analysis class at the Academy closed for the day and as I went
outside to muse on the topics discussed, a rabel was brought to my
attention. It was feeding on Musgi growing near the building that
contained my classroom. The nature of the rabel was calm and
submissive.  Its pure white coat was fluffy and supple with a decent
layer of fat between his skin and muscle.

My mouth began salivating as I felt the urge diffuse from my bones and
penetrate every organ in my body.  Without thought I picked up the
rabel. His face was unafraid and unaware of my intent. As I brought
the rabel's neck to my mouth, the rabel patiently waited with no
resistance for me to set him down and allow him to complete his
meal. Without any danger being perceived by the rabel, I closed my
jaws upon his neck. The rabel jerked quickly for a moment and I
compressed my jaws together as tightly as I could, like a shop clamp
holding material in preparation for construction.

The meat was difficult to separate from the bone and the cylindrical
shape of my teeth could not easily pierce the meat. I found myself
gnawing for long periods of time on the meat in order to separate it
from the bone and partition it into a decent size.

"My god! Holy fuck!" a voice screeched from behind.  With the quick
turn of my head I saw Satu Crimp, a peer of mine from my philosophy
classes. "Satu, she shares my mother's name" I thought to myself.

"What have you done!?" she questioned in severe shock. Her face was
pale and the distance from her hairline to her chin seemed like it was
stretched three times the length. As her original shock transferred to
a shock reflecting the calm damage of a city after a severe storm, she
said "This must be reported."

"I understand", I replied as I felt the overwhelming shame that I felt
during my trip to the grassland with my parents returning.

* . . .

"This is most unusual", Charlie Mac a biologist at the Academy
claimed. He approached a chair at the table where Gregory S. Mill, a
philosopher at the Academy, and I were seated.

"It's more than unusual", Mill stated in protest to his claim. "This
is a violation of life. Possibly the act can be considered a
murder. Ignoring whatever his act is, there has not been a murder in
centuries. How do you propose we proceed?"

"First, we can not immediately claim the act is a violation of life;
life is a fairly simple concept and may be thought of as being
incapable of being violated. It's important to note that Calais was
eating the rabel. Calais has always been a student and citizen of
sound reasoning. His psychological profile does not deviate to any
extreme point of mental illness. Therefore, what was your intention,
Calais? What purpose was served by consuming a rabel?"

While my eyes were gazing out the window I muttered, "Honestly, I am
not sure I can say. Since I was young I have wanted to eat not just
Musgi but also various animals. Other than satisfying an internal
drive, I can not state another purpose."

Professor Mac's face shifted to a state of thought. He continued the
discussion by saying, "Internal drives are characteristics of specific
species; or sub-species."

"Are you attempting to imply that Calais may be a sub-species of
human?" asked Professor Mill.

"It is a topic of consideration. If Calais is neither mad nor
defective, then he may be classified as a sub-species of the human
species." Mac replied.

"If a fundamental biological difference does exist between Calais and
the general human population, why would it not simply be considered a
disease? There are many incidences where humans have been born with a
change in their genetic structure and the change is considered a
disease and unwanted. If the change interferes with the productivity
of an individual, then the change is usually considered a disease. In
the case of Calais, the argument that Calais' actions violate the Harm
Principle and therefore make him unfit for society, could be made. An
innate quality that leads to violations of the Harm Principle is much
more severe than an innate quality that affects an individual's
productivity and quality of life." suggested Professor Mill.

Charlie Mac stated enthusiastically, "The Harm Principle does not
function well when considering what actions to take during situations
of inter-species relations. Imagine an entire race of creatures that
consume the flesh of other semi-conscious creatures as a source of
fuel; their evolution and existence is as proper as the races that do
not possess this requirement. They are not violating a Harm Principle
but instead conforming to the evolved rules of their environment. This
is not simply a question of societal ethics."

"If Calais is not considered defective and not in need of
rehabilitation, do you realize a supply of meat must be provided for
Calais?" Professor Mill asked in a provoking manner.

* . . .

Months after the incident that led to the first public awareness and
discussion of my situation, I awaited the judgment of the Academy. My
mind wandered between thoughts. No thought lasted more than a few
moments. What would be my fate? The Academy being one of the pillars
of society had the potential to do almost any act they thought was
proper; my mind did not forget the chance of being executed for being
seen as unfit and a menace.

There were three knocks at my door. A man was standing in the doorway
with a travel Musgi platter and some papers.

"Calais Hobbes, my name is Thomas Benedict. I have come to inform you
about the Academy's decision." the figure in the door stated.

I felt a heaviness within my chest. We sat down at the table and he
opened the travel platter. Inside was something strange. The object
inside reminded me of meat, but it had a slightly strange appearance.

"It's grackler meat. The meat has been cooked. It should be easier for
you to chew and digest."

Had the Academy granted me freedom? The feeling in my chest
transformed from a heavy anchor into an uncontrollable whirling
sensation.

"The meat is for you to eat. The Academy would like to end your
existence with the object you need but is unfit for our society. There
is a poison cooked into the meat. Your death will be painless and the
poison is tasteless. There will be no interference with the taste of
the grackler from the poison. Before you have your final meal, you are
free to complete a single task." the man calmly stated.

"I understand" I replied. "I would like to write a story before
supper."

* The End

